services:
  - type: web
    name: tftp-tailscale-server
    env: node
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: bash ./setup.sh
    envVars:
      - key: TAILSCALE_AUTH_KEY
        value: tskey-auth-k5oX7kEuHT11CNTRL-dy6Bnv7rMaJP4bY5XBTLaJTBSn89QyUvb
